version: '3.4'

services:
  db:
    image: postgres:9.4
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

  api:
    image: scrumble
    build:
      context: .
    volumes:
      - ./api:/app
    working_dir: /app
    depends_on:
      - db
    ports:
      - '8000:8000'
    environment:
      HOST: '0.0.0.0'
      PORT: '8000'
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
      GOOGLE_CLIENT_ID: '846194931476-lnslq69phmckpsul3ttjrcqk7msqmlqf.apps.googleusercontent.com'
      GOOGLE_API_SECRET: '***'
      TRELLO_KEY: '62bfdf783665fa1f28e1d3e324974106'
      TRELLO_SECRET: '***'
      SMTP_HOST: '***'
      SMTP_USER: '***'
      SMTP_PASS: '***'
      EMAIL_CONTACT: '***'
    command: npm run watch
